### PR TITLE
fix of moko-mvvm and mobile-multiplatform configuration

### PR DESCRIPTION
**Pull request by Alex009**
in commit messages described why changes apply

### CODE REVIEW

**Comment by rhonyabdullah** [comment]
Helo,
I try to sync and rebuild the project (and also remove .idea folder then re-import project). But looks like any _kotlin_ folder on multiplatform module not marked automatically 
kotlin sources not marked

which leading into unresolved reference while calling some kmm classes from android module.
kmm class not found

Temporary work around is to manually marking kotlin folder (or any sources folder like sqldelight) as sources root, but each time i sync the project i have to mark it again,


Also using gradle command not working, it also happened on sqldelight folder.
```kotlin
sourceSets {
        val commonMain by getting {
            resources.srcDir("src/commonMain/kotlin")
            resources.srcDir("src/commonMain/sqldelight")
        }
    }
```

**Comment by rhonyabdullah** [comment]
Temporary Workaround
```kotlin
sourceSets.all {
    java.srcDirs(project.file("src/common${it.name.capitalize()}/kotlin"))
    java.srcDirs(project.file("src/android${it.name.capitalize()}/kotlin"))
    java.srcDirs(project.file("src/ios${it.name.capitalize()}/kotlin"))
}
```

Any other idea ?

**Comment by Alex009** [comment]
yes, i see error when AS sync:
```
<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/Users/alekseymikhailovwork/Documents/development/icerockdev_workspace/github/OWeatherKMM/shared/build.gradle.kts<ij_nav><i><b>project ':kmm-library': Unable to build Kotlin project configuration</b><eol>Details: java.lang.reflect.InvocationTargetException: null<eol>Caused by: java.lang.IllegalStateException: Couldn't resolve metadata artifact for ModuleDependencyIdentifier(groupId=org.jetbrains.kotlinx, moduleId=kotlinx-coroutines-core) in configuration ':kmm-library:iosArm64CompileKlibraries'</i>
```
i fix it in new commit
image

**Comment by rhonyabdullah** [comment]
Aha, looks like this issue already fixed on moko [template](https://github.com/icerockdev/moko-template/blob/5c16cfdf85cf026f72fd069860a7945a214a8c79/mpp-library/build.gradle.kts#L31) by you @Alex009 .

**Pull request merged**
